on: [push]

name: Create App Bundle

jobs:
  bundle:
    name: Bundle ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install briefcase
      - name: Create
        run: briefcase create
      - name: Package
        if: runner.os == 'macOS'
        run: briefcase package --no-sign
      - name: Package
        if: runner.os == 'Windows'
        run: briefcase package
      - name: Upload Artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v2
        with:
          name: napari-macOS.dmg
          path: macOS/napari-0.0.1.dmg
      - name: Upload Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: napari-macOS.dmg
          path: windows/napari-0.0.1.msi